// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMj3nR5EncKx7qyCikS6FyWx9_FPyDjw',
    appId: '1:995823877944:web:4f9c970801d615f0ec4bcd',
    messagingSenderId: '995823877944',
    projectId: 'login-ui-351d5',
    authDomain: 'login-ui-351d5.firebaseapp.com',
    storageBucket: 'login-ui-351d5.appspot.com',
    measurementId: 'G-TSLTWRJ4CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0f77o-_oKsZa9echyECzfKXP48Fps-G8',
    appId: '1:995823877944:android:864e540f768ed153ec4bcd',
    messagingSenderId: '995823877944',
    projectId: 'login-ui-351d5',
    storageBucket: 'login-ui-351d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIfAYw5lIr9zaPTqaf1OQBz8S3ZRJvojw',
    appId: '1:995823877944:ios:2d9d0f84d38d19f5ec4bcd',
    messagingSenderId: '995823877944',
    projectId: 'login-ui-351d5',
    storageBucket: 'login-ui-351d5.appspot.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIfAYw5lIr9zaPTqaf1OQBz8S3ZRJvojw',
    appId: '1:995823877944:ios:2d9d0f84d38d19f5ec4bcd',
    messagingSenderId: '995823877944',
    projectId: 'login-ui-351d5',
    storageBucket: 'login-ui-351d5.appspot.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAMj3nR5EncKx7qyCikS6FyWx9_FPyDjw',
    appId: '1:995823877944:web:d0000ce188fa76d8ec4bcd',
    messagingSenderId: '995823877944',
    projectId: 'login-ui-351d5',
    authDomain: 'login-ui-351d5.firebaseapp.com',
    storageBucket: 'login-ui-351d5.appspot.com',
    measurementId: 'G-DJM35JDRHG',
  );
}
